version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: php_api
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network
    ports:
      - "8000:8000"  # Maps the container's port 8000 to the host's port 8000
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nuxt_client
    environment:
      VITE_API_URL: http://api:8000
    volumes:
      - ./client:/usr/src/app
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: